### ISSUE TITLE
Not Building With remote_receiver Component

### ISSUE THREAD

**Issue by Nicknakin** [maxgerhardt/platform-raspberrypi#21]
Environment
OS: Arch Linux x86_64 
Kernel: 6.1.6-arch1-1 
Shell: fish 3.5.1 
CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
esphome Version: 2022.12.3

```yaml
esphome:
  name: picoremote

# Example configuration entry
rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

logger:

# Enable Home Assistant API
api:
  password: "password"

ota:
  password: "password"

wifi:
  ssid: "password"
  password: "password"

remote_receiver:
  pin: GPIO22
  dump: all
  buffer_size: 512b
```

```
INFO Reading configuration picoremote.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing picoremote (board: rpipicow; framework: arduino; platform: https://github.com/maxgerhardt/platform-raspberrypi.git)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: RP2040 133MHz, 264KB RAM, 2MB Flash
 - framework-arduinopico @ 1.20604.0 (2.6.4) 
 - tool-rp2040tools @ 1.0.2 
Flash size: 2.00MB
Sketch size: 1.00MB
Filesystem size: 1.00MB
Maximium Sketch size: 1044480 EEPROM start: 0x101ff000 Filesystem start: 0x100ff000 Filesystem end: 0x101ff000
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- WiFi @ 1.0.0
|   |-- Updater @ 1.0
|   |   |-- MD5Builder @ 1.0.0
|   |   |-- LittleFS @ 0.1.0
|   |   |-- PicoOTA @ 1.0.0
|   |   |   |-- LittleFS @ 0.1.0
|   |-- MD5Builder @ 1.0.0
|   |-- lwIP-Ethernet @ 1
|   |   |-- lwIP_CYW43 @ 1
|   |   |   |-- SPI @ 1.0
|   |   |-- SPI @ 1.0
|   |-- lwIP_CYW43 @ 1
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- LEAmDNS @ 1.2
|   |-- lwIP-Ethernet @ 1
|   |   |-- lwIP_CYW43 @ 1
|   |   |   |-- SPI @ 1.0
|   |   |-- SPI @ 1.0
|   |-- WiFi @ 1.0.0
|   |   |-- Updater @ 1.0
|   |   |   |-- MD5Builder @ 1.0.0
|   |   |   |-- LittleFS @ 0.1.0
|   |   |   |-- PicoOTA @ 1.0.0
|   |   |   |   |-- LittleFS @ 0.1.0
|   |   |-- MD5Builder @ 1.0.0
|   |   |-- lwIP-Ethernet @ 1
|   |   |   |-- lwIP_CYW43 @ 1
|   |   |   |   |-- SPI @ 1.0
|   |   |   |-- SPI @ 1.0
|   |   |-- lwIP_CYW43 @ 1
|   |   |   |-- SPI @ 1.0
|   |   |-- SPI @ 1.0
|-- Updater @ 1.0
|   |-- MD5Builder @ 1.0.0
|   |-- LittleFS @ 0.1.0
|   |-- PicoOTA @ 1.0.0
|   |   |-- LittleFS @ 0.1.0
|-- MD5Builder @ 1.0.0
Linking .pioenvs/picoremote/firmware.elf
/home/nick/.platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/10.3.0/../../../../arm-none-eabi/bin/ld: .pioenvs/picoremote/src/main.cpp.o: in function `setup':
main.cpp:(.text.setup+0x468): undefined reference to `_ZTVN7esphome15remote_receiver23RemoteReceiverComponentE'
collect2: error: ld returned 1 exit status
*** [.pioenvs/picoremote/firmware.elf] Error 1
============================================================================================ [FAILED] Took 1.41 seconds ============================================================================================
```
